### ISSUE TITLE
No. of moves by knight file is causing error in cloning 

### ISSUE THREAD

**Issue by ishita2704** [chetannihith/Program-hacktoberfest24#19]
i want to work on it and rename it

**Comment by ishita2704** [comment]
![Welcome - hacktober - Visual Studio Code 21-10-2024 17_15_23](https://github.com/user-attachments/assets/bf47afea-9d42-45da-83f5-8017278b0eb5)
how to clone this

**Comment by ishita2704** [comment]
The error is likely due to the file name "No. of moves by Knight.", which contains a dot at the end. On Windows, file names that end with a period (.) or have other reserved characters (like \, /, :, *, ?, ", <, >, |) are not allowed by the file system.

**Comment by ishita2704** [comment]
pls do the review then i want to push something

**Comment by chetannihith** [comment]
![image](https://github.com/user-attachments/assets/159c9489-e5fd-4c1d-a43c-f087e0e25afb)

i have made necessary changes. you can clone this repo... Thank you!

**Comment by ishita2704** [comment]
Thanks much
